GET http://127.0.0.1:8000/TwitterNLP/test/
Content-Type: application/json

{}
###
GET http://127.0.0.1:8000/TwitterNLP/analyze/
Content-type: application/json; charset=utf-8

{
    "data": "I like this website",
    "notSoData" : "lalele",
    "anotherArray" :
    {
        "jpt" : "JP",
        "ord" : 9
    }

}

###

GET https://api.twitter.com/1.1/tweets/search/30day/dev.json?query=dave
Content-type: application/json; charset=utf-8
Authorization: Bearer AAAAAAAAAAAAAAAAAAAAACsx%2BQAAAAAA2%2F9Onm5ZIzMJotHeoJQpCFtJV10%3DSK9tQfBsNZirwauxiFzDXl80sB7M0xMGLaAbtGZkhReYFBA1Rz

{

}


###

# # 1: "khalid Send his Regards",
#  2: "LALAL werwa sdf a.sldkfqwe"
# X-CSRFToken: 'SHdSODraGrNcEjbWrZ48Qihcz4lqq10ZyWnuTozIBO9OpfWHWzwOhH5JcMeKeQEL'
# localauth: 'localapi187a0be9459e0db2:'